"use client";

import Link from "next/link";
import { ArrowRight, BookOpenCheck, Compass, ShieldCheck, UsersRound, Wrench } from "lucide-react";
import { EducationalFoundation, PillarGrid, audiencePaths } from "@/components/PlatformCards";
import { useI18n } from "@/lib/i18n";

export default function HomePage() {
  const { lang } = useI18n();
  const el = lang === "el";
  return <main>
    <section className="relative overflow-hidden bg-gradient-to-br from-[#e8fbf4] via-white to-[#fff4cf]">
      <div className="mx-auto grid max-w-7xl gap-10 px-5 py-16 lg:grid-cols-[1.05fr_.95fr] lg:items-center lg:px-8 lg:py-24">
        <div><p className="font-black uppercase tracking-wider text-mint">Moneywise · {el ? "Μάθηση για τη ζωή" : "Learning for life"}</p><h1 className="mt-4 text-5xl font-black leading-[1.05] text-ink sm:text-7xl">{el ? "Χρηματοοικονομική παιδεία για κάθε ηλικία." : "Financial literacy for every stage of life."}</h1><p className="mt-6 max-w-2xl text-xl leading-9 text-ink/68">{el ? "Κατανοούμε τα χρήματα, οργανώνουμε καλύτερα τις επιλογές μας και αποκτούμε πρακτικές δεξιότητες για κάθε στάδιο της ζωής." : "Understand money, make better decisions and build practical financial skills throughout life."}</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/onboarding" className="inline-flex items-center justify-center gap-2 rounded-full bg-ink px-7 py-4 font-black text-white shadow-premium">{el ? "Βρες τη διαδρομή σου" : "Find your path"}<ArrowRight className="h-5 w-5" /></Link><Link href="/curriculum" className="inline-flex items-center justify-center rounded-full border border-ink/15 bg-white px-7 py-4 font-black text-ink">{el ? "Δες το πρόγραμμα" : "View curriculum"}</Link></div><p className="mt-5 text-sm font-bold text-ink/55">{el ? "Δεν χρειάζεται λογαριασμός. Η πρόοδος αποθηκεύεται μόνο στη συσκευή σου." : "No account needed. Progress is stored only on your device."}</p></div>
        <div className="relative min-h-[390px] rounded-[2.5rem] bg-ink p-7 text-white shadow-premium"><div className="absolute inset-6 rounded-[2rem] border border-white/10" /><div className="relative grid h-full grid-cols-2 gap-4"><div className="rounded-[1.6rem] bg-mint p-5"><Compass className="h-10 w-10" /><p className="mt-14 text-2xl font-black">{el ? "6 μαθησιακές διαδρομές" : "6 learning paths"}</p></div><div className="mt-10 rounded-[1.6rem] bg-sun p-5 text-ink"><BookOpenCheck className="h-10 w-10" /><p className="mt-14 text-2xl font-black">{el ? "12 πυλώνες γνώσης" : "12 knowledge pillars"}</p></div><div className="rounded-[1.6rem] bg-white p-5 text-ink"><Wrench className="h-10 w-10" /><p className="mt-10 text-xl font-black">{el ? "Πρακτικά εργαλεία" : "Practical tools"}</p></div><div className="mt-8 rounded-[1.6rem] bg-grape p-5"><ShieldCheck className="h-10 w-10" /><p className="mt-10 text-xl font-black">{el ? "Ασφαλή σενάρια" : "Safe scenarios"}</p></div></div></div>
      </div>
    </section>

    <section className="mx-auto max-w-7xl px-5 py-16 lg:px-8"><p className="font-black uppercase tracking-wider text-grape">{el ? "Για κάθε στάδιο" : "For every stage"}</p><h2 className="mt-3 text-4xl font-black sm:text-5xl">{el ? "Διάλεξε τη διαδρομή που σου ταιριάζει" : "Choose the path that fits you"}</h2><div className="mt-9 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{audiencePaths.map(path => <Link key={path.id} href="/onboarding" className={`rounded-[1.75rem] bg-gradient-to-br ${path.tone} p-6 transition hover:-translate-y-1 hover:shadow-premium`}><span className="text-sm font-black">{el ? "Ηλικίες" : "Ages"} {path.ages}</span><h3 className="mt-3 text-2xl font-black">{path.title[lang]}</h3><p className="mt-3 leading-7 text-ink/65">{path.description[lang]}</p><span className="mt-5 inline-flex items-center gap-2 font-black">{el ? "Επιλογή" : "Choose"} <ArrowRight className="h-4 w-4" /></span></Link>)}</div></section>

    <section className="bg-white py-16"><div className="mx-auto max-w-7xl px-5 lg:px-8"><p className="font-black uppercase tracking-wider text-mint">{el ? "Ο κύκλος της οικονομικής ζωής" : "The financial life cycle"}</p><h2 className="mt-3 max-w-3xl text-4xl font-black sm:text-5xl">{el ? "Κοινές έννοιες, διαφορετικό βάθος για κάθε ηλικία" : "Shared concepts, different depth for every age"}</h2><p className="mt-4 max-w-3xl text-lg leading-8 text-ink/65">{el ? "Από τις πρώτες έννοιες του χρήματος μέχρι τον οικογενειακό προϋπολογισμό, την ψηφιακή ασφάλεια και τον μακροπρόθεσμο σχεδιασμό." : "From first money concepts to household budgeting, digital safety and long-term planning."}</p><div className="mt-9"><PillarGrid /></div></div></section>

    <section className="mx-auto grid max-w-7xl gap-6 px-5 py-16 lg:grid-cols-3 lg:px-8">{[[UsersRound, el ? "Οικογένειες" : "Families", el ? "Ιδέες συζήτησης και δραστηριότητες για το σπίτι." : "Conversation prompts and activities for home.", "/families"], [BookOpenCheck, el ? "Εκπαιδευτικοί και σχολεία" : "Educators and schools", el ? "Μαθησιακά αποτελέσματα και ιδέες αξιοποίησης στην τάξη." : "Learning outcomes and classroom ideas.", "/educators"], [Wrench, el ? "Πρακτικά εργαλεία" : "Practical tools", el ? "Τοπικοί υπολογισμοί με υποθετικά ή δικά σου ποσά." : "Local calculations with fictional or your own values.", "/tools"]].map(([Icon, title, body, href]) => <Link key={String(href)} href={String(href)} className="rounded-[1.75rem] bg-white p-7 shadow-soft transition hover:-translate-y-1"><Icon className="h-9 w-9 text-mint" /><h2 className="mt-5 text-2xl font-black">{String(title)}</h2><p className="mt-3 leading-7 text-ink/65">{String(body)}</p><span className="mt-5 inline-flex items-center gap-2 font-black">{el ? "Περισσότερα" : "Learn more"} <ArrowRight className="h-4 w-4" /></span></Link>)}</section>
    <section className="mx-auto max-w-7xl px-5 pb-16 lg:px-8"><EducationalFoundation /></section>
  </main>;
}

