"use client";
import Link from "next/link";
import { ArrowRight, BookOpenCheck, CheckCircle2, Clock3, Coins, Compass, GraduationCap, House, Lightbulb, ShieldCheck, Smartphone, Sparkles, UsersRound, WalletCards } from "lucide-react";
import { EducationalFoundation, audiencePaths } from "@/components/PlatformCards";
import { ClusterVisual, LifeStagesVisual, ToolPreviewVisual } from "@/components/MoneywiseVisuals";
import { curriculumPillars } from "@/data/platform";
import { useI18n } from "@/lib/i18n";

const clusters=[
 {type:"everyday" as const,title:{el:"Χρήμα και καθημερινές αποφάσεις",en:"Money and everyday decisions"},indexes:[0,1,2]},
 {type:"planning" as const,title:{el:"Οργάνωση και προγραμματισμός",en:"Organisation and planning"},indexes:[3,4,5]},
 {type:"protection" as const,title:{el:"Προστασία και υπευθυνότητα",en:"Protection and responsibility"},indexes:[6,7,9]},
 {type:"future" as const,title:{el:"Ανάπτυξη και μέλλον",en:"Growth and future"},indexes:[8,10,11]}
];
const pathTitles=["Ανακαλύπτω τα χρήματα","Χτίζω έξυπνες οικονομικές συνήθειες","Προετοιμάζομαι για τις πρώτες μου αποφάσεις","Οργανώνω την οικονομική μου ανεξαρτησία","Διαχειρίζομαι το σήμερα και σχεδιάζω το αύριο","Οργανώνω και προστατεύω τους πόρους μου"];
const pathIcons=[Coins,Lightbulb,Smartphone,WalletCards,House,ShieldCheck];

export default function HomePage(){
 const{lang}=useI18n();const el=lang==="el";
 return <main className="public-home">
  <section className="bg-[#fbfcfa]"><div className="mx-auto grid max-w-7xl gap-12 px-5 py-14 lg:grid-cols-[1.02fr_.98fr] lg:items-center lg:px-8 lg:py-20"><div><p className="text-sm font-extrabold text-mint">{el?"Μάθηση για πραγματικές αποφάσεις":"Learning for real decisions"}</p><h1 className="mt-4 max-w-3xl text-5xl font-black leading-[1.06] tracking-[-.035em] sm:text-7xl">{el?"Χρηματοοικονομική παιδεία για κάθε ηλικία.":"Financial literacy for every stage of life."}</h1><p className="mt-6 max-w-2xl text-xl leading-9 text-ink/70">{el?"Πρακτικά μαθήματα, απλές εξηγήσεις και διαδραστικές δραστηριότητες που βοηθούν παιδιά, εφήβους και ενήλικες να λαμβάνουν καλύτερες οικονομικές αποφάσεις.":"Practical lessons, plain explanations and interactive activities that help children, teenagers and adults make better financial decisions."}</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/onboarding" className="inline-flex min-h-14 items-center justify-center gap-2 rounded-xl bg-ink px-7 font-extrabold text-white shadow-soft">{el?"Βρες τη διαδρομή σου":"Find your path"}<ArrowRight className="h-5 w-5"/></Link><Link href="/curriculum" className="inline-flex min-h-14 items-center justify-center rounded-xl border border-ink/15 bg-white px-7 font-extrabold">{el?"Εξερεύνησε το πρόγραμμα":"Explore the programme"}</Link></div><div className="mt-6 flex max-w-xl items-start gap-3 border-t border-ink/10 pt-5 text-sm text-ink/60"><ShieldCheck className="h-5 w-5 shrink-0 text-mint"/><p>{el?"Δεν απαιτούνται πραγματικά οικονομικά ή τραπεζικά στοιχεία.":"Real financial or banking details are not required."}</p></div></div><LifeStagesVisual/></div></section>

  <section className="age-path-section mx-auto max-w-7xl px-4 py-14 sm:px-5 sm:py-16 lg:px-8"><div className="max-w-3xl"><p className="text-sm font-extrabold text-grape">{el?"Έξι διαδρομές, μία κοινή βάση":"Six paths, one shared foundation"}</p><h2 className="mt-3 text-4xl font-black sm:text-5xl">{el?"Μια διαδρομή μάθησης για κάθε στάδιο της ζωής":"A learning path for every stage of life"}</h2><p className="mt-4 text-lg leading-8 text-ink/65">{el?"Η γλώσσα, τα παραδείγματα και οι δραστηριότητες προσαρμόζονται στις ανάγκες κάθε ηλικίας.":"Language, examples and activities adapt to every age."}</p></div><div className="mt-8 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{audiencePaths.map((path,index)=>{const topics=path.description[lang].split(",").slice(0,3);const Icon=pathIcons[index];return <article key={path.id} className="flex min-h-[19rem] flex-col rounded-[1.5rem] border border-ink/10 bg-white p-5 transition hover:-translate-y-1 hover:shadow-premium sm:p-6"><div className="flex items-center justify-between gap-3"><span className="rounded-full bg-cloud px-3 py-1.5 text-sm font-extrabold">{el?"Ηλικίες":"Ages"} {path.ages}</span><span className={`grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-gradient-to-br ${path.tone}`} aria-hidden="true"><Icon className="h-6 w-6"/></span></div><h3 className="mt-5 text-[1.35rem] font-black leading-8 sm:text-2xl">{el?pathTitles[index]:path.title.en}</h3><div className="mt-4 flex flex-wrap gap-2">{topics.map(topic=><span key={topic} className="inline-flex min-h-8 items-center rounded-full bg-cloud px-3 py-1.5 text-sm font-bold leading-5 text-ink/70">{topic.trim()}</span>)}</div><Link href="/onboarding" aria-label={`${el?"Επίλεξε διαδρομή":"Choose path"}: ${el?pathTitles[index]:path.title.en}`} className="mt-auto inline-flex min-h-11 w-full items-center justify-between gap-2 pt-5 font-extrabold">{el?"Επίλεξε διαδρομή":"Choose path"}<ArrowRight className="h-4 w-4 shrink-0"/></Link></article>})}</div></section>

  <section className="bg-white py-16"><div className="mx-auto max-w-7xl px-5 lg:px-8"><p className="text-sm font-extrabold text-mint">{el?"Ο οικονομικός κύκλος":"The financial life cycle"}</p><h2 className="mt-3 max-w-3xl text-4xl font-black sm:text-5xl">{el?"Δώδεκα πυλώνες σε τέσσερις καθαρές ενότητες":"Twelve pillars in four clear groups"}</h2><div className="mt-9 grid gap-5 md:grid-cols-2">{clusters.map(cluster=><details key={cluster.type} className="group rounded-[1.6rem] border border-ink/10 bg-[#fbfcfa] p-5 open:shadow-soft"><summary className="cursor-pointer list-none"><ClusterVisual type={cluster.type}/><div className="mt-5 flex items-center justify-between gap-4"><h3 className="text-xl font-black">{cluster.title[lang]}</h3><span className="grid h-9 w-9 place-items-center rounded-full bg-white text-xl font-black group-open:rotate-45">+</span></div></summary><ul className="mt-5 grid gap-2 border-t border-ink/10 pt-4">{cluster.indexes.map(i=><li key={i} className="flex items-center gap-3 rounded-xl bg-white p-3"><CheckCircle2 className="h-5 w-5 text-mint"/><span className="font-bold">{curriculumPillars[i][1][lang]}</span></li>)}</ul></details>)}</div></div></section>

  <section className="mx-auto max-w-7xl px-5 py-16 lg:px-8"><h2 className="text-4xl font-black sm:text-5xl">{el?"Πώς λειτουργεί το Moneywise":"How Moneywise works"}</h2><ol className="mt-9 grid gap-5 md:grid-cols-4">{[[Compass,el?"Επιλέγεις τη διαδρομή σου":"Choose your path"],[BookOpenCheck,el?"Μαθαίνεις σε σύντομα και κατανοητά βήματα":"Learn in short, clear steps"],[Sparkles,el?"Εξασκείσαι σε πραγματικά καθημερινά σενάρια":"Practise in real everyday scenarios"],[Clock3,el?"Παρακολουθείς την πρόοδό σου":"Track your progress"]].map(([Icon,title],i)=><li key={String(title)} className="border-t-2 border-ink/10 pt-5"><span className="text-sm font-black text-mint">0{i+1}</span><Icon className="mt-5 h-8 w-8"/><h3 className="mt-4 text-xl font-black">{String(title)}</h3></li>)}</ol></section>

  <section className="bg-[#f3f7f7] py-16"><div className="mx-auto max-w-7xl px-5 lg:px-8"><p className="text-sm font-extrabold text-coral">{el?"Πρακτική μάθηση":"Practical learning"}</p><h2 className="mt-3 text-4xl font-black sm:text-5xl">{el?"Δραστηριότητες από την καθημερινή ζωή":"Activities drawn from everyday life"}</h2><div className="mt-9 grid gap-5 lg:grid-cols-3">{[["budget",el?"Οργάνωση προϋπολογισμού":"Budget organisation",el?"Μοίρασε ένα υποθετικό εισόδημα σε ανάγκες, στόχους και επιλογές.":"Allocate fictional income to needs, goals and choices."],["shopping",el?"Έξυπνη σύγκριση αγορών":"Smart shopping comparison",el?"Σύγκρινε τιμή, ποσότητα και χρησιμότητα πριν επιλέξεις.":"Compare price, quantity and usefulness before choosing."],["scam",el?"Προστασία από ψηφιακές απάτες":"Protection from digital scams",el?"Εντόπισε πίεση, ύποπτους συνδέσμους και αιτήματα για κωδικούς.":"Spot urgency, suspicious links and password requests."]].map(([type,title,body])=><article key={type} className="rounded-[1.6rem] bg-white p-5 shadow-soft"><ToolPreviewVisual type={type as "budget"|"shopping"|"scam"}/><h3 className="mt-5 text-2xl font-black">{title}</h3><p className="mt-3 leading-7 text-ink/65">{body}</p><Link href="/tools" className="mt-5 inline-flex items-center gap-2 font-extrabold">{el?"Δοκίμασε το εργαλείο":"Try the tool"}<ArrowRight className="h-4 w-4"/></Link></article>)}</div></div></section>

  <section className="mx-auto max-w-7xl px-5 py-16 lg:px-8"><p className="text-sm font-extrabold text-mint">{el?"Διαφάνεια πηγών":"Transparent sources"}</p><h2 className="mb-7 mt-2 text-4xl font-black">{el?"Επιστημονική και εκπαιδευτική βάση":"Scientific and educational foundation"}</h2><EducationalFoundation/></section>

  <section className="bg-white py-16"><div className="mx-auto max-w-7xl px-5 lg:px-8"><h2 className="text-4xl font-black">{el?"Για ποιον είναι το Moneywise;":"Who is Moneywise for?"}</h2><div className="mt-8 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{[[Sparkles,el?"Παιδιά και έφηβοι":"Children and teenagers",el?"Κατανοητές έννοιες και ασφαλείς καθημερινές επιλογές.":"Clear concepts and safe everyday choices.","/onboarding"],[Compass,el?"Ενήλικες":"Adults",el?"Πρακτική οικονομική οργάνωση για κάθε στάδιο της ζωής.":"Practical financial organisation for every stage.","/adults"],[UsersRound,el?"Οικογένειες":"Families",el?"Ιδέες συζήτησης και δραστηριότητες για το σπίτι.":"Conversation ideas and home activities.","/families"],[GraduationCap,el?"Εκπαιδευτικοί και σχολεία":"Educators and schools",el?"Υλικό με σαφείς στόχους και ιδέες αξιοποίησης.":"Material with clear outcomes and activity ideas.","/educators"]].map(([Icon,title,body,href])=><article key={String(title)} className="flex flex-col rounded-[1.4rem] border border-ink/10 p-5"><Icon className="h-7 w-7 text-mint"/><h3 className="mt-5 text-xl font-black">{String(title)}</h3><p className="mt-2 leading-7 text-ink/60">{String(body)}</p><Link href={String(href)} className="mt-auto inline-flex items-center gap-2 pt-5 font-extrabold">{el?"Μάθε περισσότερα":"Learn more"}<ArrowRight className="h-4 w-4"/></Link></article>)}</div></div></section>

  <section className="mx-auto max-w-7xl px-5 py-16 lg:px-8"><div className="rounded-[1.7rem] bg-[#edf7f8] p-7 sm:p-9"><div className="grid gap-7 lg:grid-cols-[.7fr_1.3fr]"><div><ShieldCheck className="h-10 w-10 text-mint"/><h2 className="mt-4 text-3xl font-black">{el?"Μάθηση με ασφάλεια και διαφάνεια":"Safe and transparent learning"}</h2></div><ul className="grid gap-3 sm:grid-cols-2">{(el?["Δεν χρησιμοποιούνται πραγματικά χρήματα.","Δεν απαιτείται σύνδεση με τράπεζα.","Δεν καταχωρίζεις τραπεζικά στοιχεία.","Οι δραστηριότητες είναι εκπαιδευτικές.","Δεν παρέχονται προσωπικές οικονομικές συμβουλές.","Η πρόοδος αποθηκεύεται τοπικά στη συσκευή."]:["No real money is used.","No bank connection is required.","Do not enter banking details.","Activities are educational.","No personalised financial advice is provided.","Progress is stored locally on the device."]).map(item=><li key={item} className="flex items-start gap-2 rounded-xl bg-white p-3 text-sm font-bold"><CheckCircle2 className="h-4 w-4 shrink-0 text-mint"/>{item}</li>)}</ul></div></div></section>

  <section className="px-5 pb-20 lg:px-8"><div className="mx-auto max-w-7xl rounded-[2rem] bg-ink px-7 py-12 text-center text-white"><h2 className="mx-auto max-w-4xl text-4xl font-black sm:text-5xl">{el?"Κάνε το πρώτο βήμα προς καλύτερες οικονομικές αποφάσεις.":"Take the first step towards better financial decisions."}</h2><Link href="/onboarding" className="mt-8 inline-flex min-h-14 items-center gap-2 rounded-xl bg-white px-7 font-extrabold text-ink">{el?"Ξεκίνα τη διαδρομή σου":"Start your path"}<ArrowRight className="h-5 w-5"/></Link></div></section>
 </main>
}
