"use client";
import { useMemo, useState } from "react";
import { Calculator, Info, RotateCcw, ShieldCheck } from "lucide-react";
import { PageHeader } from "@/components/PlatformCards";
import { useI18n } from "@/lib/i18n";

const tools = [
  ["saving","Στόχος αποταμίευσης","Savings Goal Planner"],["budget","Μηνιαίος προϋπολογισμός","Monthly Budget Builder"],
  ["needs","Ανάγκες και επιθυμίες","Needs vs Wants"],["shopping","Σύγκριση αγορών","Smart Shopping Comparison"],
  ["emergency","Αποθεματικό έκτακτης ανάγκης","Emergency Fund Explainer"],["interest","Οπτικοποίηση τόκου","Interest Visualiser"],
  ["inflation","Οπτικοποίηση πληθωρισμού","Inflation Visualiser"],["subscriptions","Έλεγχος συνδρομών","Subscription Review"],
  ["scam","Εξάσκηση εντοπισμού απάτης","Scam-Spotting Practice"],["household","Σενάριο οικογενειακού προϋπολογισμού","Household Budget Scenario"]
];
export default function ToolsPage(){
 const {lang}=useI18n(); const el=lang==="el"; const [active,setActive]=useState("saving"); const [a,setA]=useState(1200); const [b,setB]=useState(100); const [c,setC]=useState(3);
 const result=useMemo(()=>{if(active==="saving")return b>0?Math.ceil(Math.max(0,a)/b):0;if(active==="budget"||active==="household")return a-b;if(active==="emergency")return b*c;if(active==="interest")return a*Math.pow(1+c/100,b)-a;if(active==="inflation")return a/Math.pow(1+c/100,b);if(active==="subscriptions")return b*12;if(active==="shopping")return Math.min(a,b);return 0},[active,a,b,c]);
 const labels=active==="saving"?[el?"Στόχος (€)":"Goal (€)",el?"Ποσό ανά μήνα (€)":"Monthly amount (€)",el?"Μήνες που χρειάζονται":"Months needed"]:active==="budget"||active==="household"?[el?"Μηνιαίο εισόδημα (€)":"Monthly income (€)",el?"Συνολικές δαπάνες (€)":"Total expenses (€)",el?"Υπόλοιπο":"Balance"]:active==="emergency"?[el?"Διαθέσιμο ποσό (€)":"Available amount (€)",el?"Βασικές μηνιαίες δαπάνες (€)":"Essential monthly expenses (€)",el?"Μήνες στόχου":"Target months"]:active==="interest"?[el?"Αρχικό ποσό (€)":"Initial amount (€)",el?"Έτη":"Years",el?"Υποθετικό επιτόκιο (%)":"Illustrative rate (%)"]:active==="inflation"?[el?"Σημερινό ποσό (€)":"Current amount (€)",el?"Έτη":"Years",el?"Υποθετικός πληθωρισμός (%)":"Illustrative inflation (%)"]:active==="subscriptions"?[el?"Μηνιαίο διαθέσιμο ποσό (€)":"Monthly available amount (€)",el?"Συνδρομές ανά μήνα (€)":"Monthly subscriptions (€)",el?"Ετήσιο κόστος":"Annual cost"]: [el?"Τιμή Α (€)":"Price A (€)",el?"Τιμή Β (€)":"Price B (€)",el?"Χαμηλότερη τιμή":"Lower price"];
 const special=active==="needs"||active==="scam";
 function reset(){setA(1200);setB(100);setC(3)}
 return <main className="mx-auto max-w-7xl px-5 py-8 lg:px-8"><PageHeader eyebrow={el?"Πρακτικά εργαλεία":"Practical tools"} title={el?"Δοκίμασε, σύγκρινε, κατανόησε":"Try, compare, understand"} body={el?"Όλοι οι υπολογισμοί γίνονται στη συσκευή σου. Χρησιμοποίησε υποθετικά ποσά — δεν χρειάζονται πραγματικά οικονομικά ή τραπεζικά στοιχεία.":"All calculations happen on your device. Use fictional values—real financial or banking details are not needed."}/>
 <div className="mt-8 grid gap-6 lg:grid-cols-[330px_1fr]"><nav className="grid h-fit gap-2" aria-label={el?"Εργαλεία":"Tools"}>{tools.map(([id,gr,en])=><button key={id} onClick={()=>setActive(id)} className={`min-h-14 rounded-2xl px-4 text-left font-black ${active===id?"bg-ink text-white":"bg-white text-ink"}`}>{lang==="el"?gr:en}</button>)}</nav>
 <section className="rounded-[2rem] bg-white p-6 shadow-premium sm:p-9"><Calculator className="h-10 w-10 text-mint"/><h2 className="mt-4 text-3xl font-black">{(tools.find(x=>x[0]===active)??tools[0])[el?1:2]}</h2>{special?<div className="mt-7 space-y-4"><p className="rounded-2xl bg-cloud p-5 text-lg font-bold">{active==="needs"?(el?"Ένα ζεστό μπουφάν τον χειμώνα είναι συνήθως ανάγκη. Ένα δεύτερο ίδιο μπουφάν επειδή είναι σε προσφορά είναι συνήθως επιθυμία.":"A warm winter coat is usually a need. A second identical coat just because it is on sale is usually a want."):(el?"Μήνυμα: «Ο λογαριασμός σου κλειδώθηκε. Πάτησε τώρα και γράψε τον κωδικό σου.»":"Message: “Your account is locked. Tap now and enter your password.”")}</p><div className="rounded-2xl border border-mint/30 bg-emerald-50 p-5"><ShieldCheck className="h-6 w-6 text-mint"/><p className="mt-3 font-black">{active==="needs"?(el?"Ρώτησε: το χρειάζομαι τώρα, μπορώ να το χρησιμοποιήσω και χωρά στον προϋπολογισμό;":"Ask: do I need it now, will I use it, and does it fit the budget?"):(el?"Ύποπτο: πίεση χρόνου, αίτημα για κωδικό και άγνωστος σύνδεσμος. Μην πατήσεις. Επικοινώνησε από το επίσημο κανάλι.":"Suspicious: urgency, a password request and an unknown link. Do not tap. Contact the provider through its official channel.")}</p></div></div>:<div className="mt-7 grid gap-4 sm:grid-cols-3"><label className="font-bold">{labels[0]}<input type="number" value={a} onChange={e=>setA(Number(e.target.value))} className="mt-2 w-full rounded-2xl border border-ink/15 p-4 text-xl"/></label><label className="font-bold">{labels[1]}<input type="number" value={b} onChange={e=>setB(Number(e.target.value))} className="mt-2 w-full rounded-2xl border border-ink/15 p-4 text-xl"/></label>{["emergency","interest","inflation"].includes(active)&&<label className="font-bold">{labels[2]}<input type="number" value={c} onChange={e=>setC(Number(e.target.value))} className="mt-2 w-full rounded-2xl border border-ink/15 p-4 text-xl"/></label>}<div className="rounded-2xl bg-ink p-5 text-white sm:col-span-3"><p className="text-sm font-black text-white/60">{labels[2]}</p><p className="mt-2 text-4xl font-black">{Number.isFinite(result)?result.toLocaleString(lang==="el"?"el-GR":"en-US",{maximumFractionDigits:2}):"—"}{active==="saving"?"": " €"}</p><p className="mt-3 text-white/70">{el?"Το αποτέλεσμα είναι εκπαιδευτικό παράδειγμα και όχι προσωπική οικονομική συμβουλή. Επιτόκια, πληθωρισμός και μελλοντικές αποδόσεις δεν είναι εγγυημένα.":"This result is an educational example, not personal financial advice. Rates, inflation and future returns are not guaranteed."}</p></div></div>}
 <button onClick={reset} className="mt-6 inline-flex min-h-11 items-center gap-2 rounded-xl bg-cloud px-4 text-sm font-extrabold"><RotateCcw className="h-4 w-4"/>{el?"Επαναφορά παραδείγματος":"Reset example"}</button>
 <div className="mt-7 flex gap-3 rounded-2xl bg-amber-50 p-4 text-sm leading-6 text-ink/70"><Info className="h-5 w-5 shrink-0 text-amber-700"/><p>{el?"Τα δεδομένα δεν αποστέλλονται ούτε αποθηκεύονται. Μην καταχωρίζεις αριθμούς λογαριασμών, καρτών ή άλλα ευαίσθητα στοιχεία.":"Data is not sent or stored. Do not enter account or card numbers, or other sensitive details."}</p></div></section></div></main>
}
